from database import Database
import random, time


MENU_PROMPT = """Welcome in my game. Here are your options:
p - play the game
r - change range of numbers
c - change number of lives
s - show top 10 scores
q - to quit the game

Your choice: """

CHANCES = 5

RANGE_LIST = [0, 20]

def random_number(range_list):
    """" random number generator"""
    rand_num = random.randint(*range_list)
    return rand_num


def change_chances():
    """Function to change amount of lives in game"""
    global CHANCES
    new_chances = int(input("How many lives do you want to have? "))
    CHANCES = new_chances

def change_range():
    """Function to change range of guessing numbers"""
    global RANGE_LIST
    print("Your range can't be smaller than 10. ")
    try:
        starting_number = int(input("Select starting number: "))
        ending_number = int(input("Select ending number: "))
    except ValueError:
        print("Pick correct value! ")
    if ending_number < starting_number:
        starting_number, ending_number = ending_number, starting_number
    if ending_number - starting_number < 10:
        print("You need to pick bigger range!")
        change_range()
    else:
        RANGE_LIST = [starting_number, ending_number + 1]


def score_counter(chances, chances_left):
    score = 101 - (chances - chances_left)
    return score


def show_scores():
    print("Leaderboard:")
    for score in Database.get_top_ten_scores(Database):
        print(f'Player - {score[1]} scored - {score[2]} in range {score[3]}')


def guess_the_number():
    """Game core"""
    global RANGE_LIST
    global CHANCES
    chances_left = CHANCES
    range_list = RANGE_LIST
    computer_number = random_number(RANGE_LIST)
    name = input("Please enter your name: ")
    print(f"""Good luck {name}! Try to guess number generated by computer. You have only {chances_left} chances to make it.
A number is between {range_list[0]} and {range_list[1] - 1}. Try your best. """)

    while chances_left:
        user_input = input(f"Pick a number between {range_list[0]} and {range_list[1]-1}: ")
        try:
            user_input = int(user_input)
            if user_input < range_list[0] or user_input > range_list[1]:
                print(f"Pick right value between {range_list[0]} and {range_list[1]-1}")
            else:
                

                if computer_number > user_input:
                    print("Computer number is bigger than yours!")
                    chances_left -= 1
                    print(f"You have {chances_left} chances left.")
                    if chances_left == 0:
                        print(f"Computer number was: {computer_number}")

                elif computer_number < user_input:
                    print("Computer number is lower than yours!")
                    chances_left -= 1
                    print(f"You have {chances_left} chances left.")
                    if chances_left == 0:
                        print(f"Computer number was: {computer_number}")
                else:
                    print("You guessed right! Congratulations!\n\n")
                    score = score_counter(CHANCES, chances_left)
                    range_string = f"({RANGE_LIST[0]} - {RANGE_LIST[1]-1})"
                    Database.insert_new_scores(Database, name, score, range_string)
                    chances_left = 0
                    time.sleep(5)

        except ValueError:
            print("Pick correct value!")


USER_OPTIONS = {  #dictionary with functions
    'p': guess_the_number,
    'c': change_chances,
    'r': change_range,
    's': show_scores,
}


def menu():
    """Menu for the program"""
    Database.create_scores_table(Database)
    selection = input(MENU_PROMPT)
    while selection != 'q':
        if selection in USER_OPTIONS:
            selected_function = USER_OPTIONS[selection]
            selected_function()
            selection = input(MENU_PROMPT)
        else:
            print("Pick correct value")
    
    print("Have a nice day!")

menu()
